modLoader = "lowcodefml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/rrls/issues"
license = "OSL-3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "rrls"
version = "${version}"
displayURL = "https://curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reloading Screen"
updateJSONURL = "https://api.modrinth.com/updates/rrls/forge_updates.json"
authors = "dima_dencep"
credits = "ne4t0gg, nneewwtt, Madis0, notlin, Amirhan-Taipovjan, GodGun968, TheBossMagnus, LostLuma, FITFC, Gazmanovich"
description = "Makes resource packs load in the background, allowing you to do other things while waiting!"
logoFile = "icon.png"

[[mixins]]
config = "rrls.mixins.json"
[[mixins]]
config = "rrls-common.mixins.json"

[[dependencies.rrls]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "roughlyenoughconfigscreens"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.rrls]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
