modLoader = "lowcodefml" # javafml
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/rrls/issues"
license = "OSL-3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "rrls"
version = "${project.version}"
displayURL = "https://curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reloading Screen"
# updateJSONURL = "https://api.modrinth.com/updates/rrls/forge_updates.json"
authors = "dima_dencep"
credits = "ne4t0gg, nneewwtt, Madis0, notlin, oldveseliyschoolnik, GodGun968, TheBossMagnus, LostLuma, FITFC, Gazmanovich, TheLegendofSaram, thesh1xx, yichifauzi"
description = "Makes resource packs load in the background, allowing you to do other things while waiting!"
logoFile = "icon.png"

[[mixins]]
config = "rrls.mixins.json"
[[mixins]]
config = "rrls-forge.mixins.json"

[[dependencies.rrls]]
modId = "neoforge"
type = "required"
versionRange = "[${project.forge_version},]"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
type = "required"
versionRange = "[${project.minecraft_version},)"
ordering = "NONE"
side = "BOTH"
