import org.redlance.dima_dencep.gradle.publish2discord.tasks.PublishDiscordTask

plugins {
    id "org.redlance.dima_dencep.gradle.PublishToDiscord" version "1.0.8"
    id "com.gradleup.shadow" version "9.4.2"
    id "xyz.wagyourtail.unimined" version "1.4.2+redlance.3"
    id "net.neoforged.licenser" version "0.7.5"
    id "org.redlance.dima_dencep.gradle.machete"  version "2.0.0"
}

license {
    header = rootProject.file('HEADER')
    skipExistingHeaders = false

    tasks {
        rrls {
            files.from rootProject.fileTree("src", {
                include "**/*.java"
            })
        }
    }
}

base.archivesName = rootProject.archives_base_name
version = "${rootProject.mod_version}+mc.${rootProject.minecraft_version}"
group = rootProject.maven_group

sourceSets {
    fabric
    neoforge
}

repositories {
    mavenLocal()
    maven {
        name = "RedlancePublic"
        url = "https://repo.redlance.org/public"
    }
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

configurations {
    shadow
}

unimined.minecraft(sourceSets.main) {
    version minecraft_version

    fabric {
        loader fabric_loader_version
        accessWidener file("src/main/resources/rrls.classtweaker")
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    fabric {
        loader fabric_loader_version
        accessWidener file("src/main/resources/rrls.classtweaker")
    }
    defaultRemapJar = true
}

unimined.minecraft(sourceSets.neoforge) {
    combineWith(sourceSets.main)

    neoForge {
        loader("net.neoforged:neoforge:$neoforge_version:universal")
        mixinConfig("rrls.mixins.json", "rrls-forge.mixins.json")

        accessTransformer(provider {
            def transformed = file("src/main/resources/rrls.classtweaker").text
                    .replaceFirst(/classTweaker\s+v\d+\s+(\S+)/, 'accessWidener v2 $1')
                    .readLines()
                    .findAll { line ->
                        !line.trim().startsWith("transitive-inject-interface") && !line.trim().startsWith("inject-interface")
                    }
                    .join("\n")

            def out = layout.buildDirectory.file("generated/rrls.classtweaker").get().asFile
            try {
                out.parentFile.mkdirs()
                out.write(transformed)
                return aw2at(out)
            } finally {
                out.delete()
            }
        }.get())
    }
    defaultRemapJar = true
}

dependencies {
    // Core
    shadow("org.redlance.common-utils:services:$commonutils_version") {
        transitive = false

        neoforgeImplementation it
        fabricImplementation it
        implementation it
    }

    // Common
    implementation("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${fcapip_version}")
    compileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcapip_version}") {
        transitive = false
    }

    // Fabric
    fabricImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    fabricCompileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcapip_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    fabricCompileOnly(fabricApi.fabricModule("fabric-resource-loader-v1", "0.146.0+26.1.2"))

    // Neoforge
}

shadowJar {
    configurations = [project.configurations.shadow]
    relocate "org.redlance.common", "org.redlance.dima_dencep.mods.rrls"

    from(tasks.named("remapFabricJar").map { zipTree(it.archiveFile) })
    from(tasks.named("remapNeoforgeJar").map { zipTree(it.archiveFile) })

    archiveClassifier.set null

    // Services
    filesMatching('META-INF/services/**') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    mergeServiceFiles()

    // Fix fabric jij
    filesMatching("META-INF/jarjar/*.jar") {
        path = path.replace("META-INF/jarjar/", "META-INF/jars/")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    filesMatching('META-INF/jarjar/metadata.json') {
        filter { it.replace('META-INF/jarjar/', 'META-INF/jars/') }
    }

    // Other
    exclude 'org/redlance/dima_dencep/mods/rrls/utils/GuiGraphicsGenerator**'
}

[tasks.processResources, tasks.processFabricResources, tasks.processNeoforgeResources].each {
    def buildProps = rootProject.properties.clone()
    buildProps.put("version", version)

    // Another workaround
    buildProps.put("fabric_minecraft_version", minecraft_version.replace('-snapshot-', '-alpha.'))

    it.filesMatching(["META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
        expand buildProps
    }
}

machete {
    tasks.set(Collections.singleton("shadowJar"))
    sourceFileStriping.enabled = true

    png.compressionLevel.set(9)
    png.compressorIterations.set(32)
    png.enabled = false
}

tasks.register("publishToDiscord", PublishDiscordTask) {
    username.set("Remove Reloading Screen Updates")
    url.set(providers.environmentVariable("DISCORD_WEBHOOK"))
    avatar.set("https://raw.githubusercontent.com/dima-dencep/rrls/HEAD/src/main/resources/icon.png")

    container {
        it.title = "## ✨ Remove Reloading Screen\n### v${version} is out!"
        it.description = "### What's new:\n${providers.environmentVariable("MOD_CHANGELOG").orElse("").get()}"

        it.thumbnail("https://raw.githubusercontent.com/dima-dencep/rrls/HEAD/src/main/resources/icon.png")
        it.timestamp(System.currentTimeMillis())
    }

    links {
        it.fromEnvHack()
    }

    footer = "||<@&1136395468809707642>||"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set 25
}

jar {
    archiveClassifier.set "dev"
}
