# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 26.1-snapshot-6
    fabric_loader_version = 0.18.4
    neoforge_version = 26.1.0.0-alpha.0+snapshot-6.20260203.212009

# Mod Properties
    mod_version = 5.1.15
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = rrls

# Dependencies
    fcapip_version = 21.11.1
    commonutils_version = 1.0.6
