# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 26.2
    fabric_loader_version = 0.19.3
    neoforge_version = 26.2.0.41-beta

# Mod Properties
    mod_version = 5.2.8
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = rrls

# Dependencies
    fcapip_version = 26.2.1
    commonutils_version = 1.3.8
