loom {
    accessWidenerPath = file("src/main/resources/rrls.accesswidener")
}

dependencies {
    modCompileOnly "net.fabricmc:fabric-loader:${loader_version}"

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${fcapip_version}"
    modCompileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcapip_version}") {
        transitive = false
    }
}

jar {
    from rootProject.file("LICENSE")
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
}
